# Generated by Django 3.1.3 on 2020-11-11 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blog', '0003_groupmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupModel',
        ),
    ]
